- name: Setup Flask App on EC2
  hosts: flask_server
  become: yes

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop the existing Flask app container (if any)
      docker_container:
        name: flask-app-container
        state: stopped
        ignore_errors: yes

    - name: Remove the existing Flask app container (if any)
      docker_container:
        name: flask-app-container
        state: absent
        ignore_errors: yes

    - name: Pull Flask Docker image
      docker_image:
        name: omkarsg07/flask-app
        source: pull
        tag: latest

    - name: Run Flask app container
      docker_container:
        name: flask-app-container
        image: omkarsg07/flask-app:latest
        state: started
        restart_policy: always
        exposed_ports:
          - "5000"
        published_ports:
          - "5000:5000"
        detach: yes
