- name: Setup Flask App on EC2
  hosts: flask_server
  become: yes

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop existing Flask app container (if running)
      docker_container:
        name: flask-app-container
        state: stopped
        ignore_errors: yes   # Ignore errors if the container is not running

    - name: Remove existing Flask app container
      docker_container:
        name: flask-app-container
        state: absent
        ignore_errors: yes

    - name: Pull the latest Flask Docker image from Docker Hub
      docker_image:
        name: omkarsg07/flask-app
        tag: latest
        source: pull

    - name: Run the Flask app container with latest image
      docker_container:
        name: flask-app-container
        image: omkarsg07/flask-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
        detach: yes
