name: CI - Feature Branch Test

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flask

      - name: Run basic test
        run: |
          echo "Running basic test (placeholder)"
          python app.py &
          sleep 5
          curl -f http://localhost:5000/
