name: Deploy Flask App to EC2 using Ansible

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible and Terraform
      run: |
        sudo apt update
        sudo apt install -y ansible unzip
        curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version

    - name: Terraform Init
      working-directory: terraform-aws
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve

    - name: Get EC2 IP from Terraform Output and write to Ansible inventory
      working-directory: terraform-aws
      run: |
        EC2_IP=$(terraform output -raw ec2_public_ip)
        echo "[flask]" > ../ansible/inventory.ini
        echo "$EC2_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../ansible/inventory.ini

    - name: Save EC2 SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/playbook.yml -i ansible/inventory.ini
