name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # main branch push works on main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # GitHub Repo 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Docker Buildx 

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  
        push: true   # Docker Image psuh
        tags: omkarsg07/flask-app:latest  # Docker Hub tag
